---
version: "3.9"

services:
  oracle-db:
    # You need to build the image locally first
    # https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/README.md
    image: container-registry.oracle.com/database/free:latest
    ports:
      - '1521:1521'
    shm_size: 8g
    environment:
      ORACLE_PDB: ${ORACLE_PDB}
      ORACLE_PWD: ${ORACLE_PWD}
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
    driver: local
