version: "3.8"

services:
  tensorflow-notebook:
      image: quay.io/jupyter/tensorflow-notebook
      volumes:
          - 'jupyter_home:/home/jovyan'
      ports:
        - 8888:8888

volumes:
  jupyter_home:
    driver: local
