version: '3'

services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    environment:
      - jenkins_home=/var/jenkins_home
    ports:
      - '8080:8080'
    volumes:
      - 'jenkins_home:/var/jenkins_home'

volumes:
  jenkins_home:
    driver: local
